### ISSUE TITLE
Testing completely anonymous contributions

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Contribution#57]
This aims to let people  without having to provide an email address.

In the settings, "Simple" is basically renamed to "Open" contributions. There's a new checkbox to allow anonymous contributions. Both have to be checked to allow anonymous contributions.

On the public side, an anonymous user can now check the 'Keep identity private' box, which will basically just make up an email address for the user.

So, things to look at are just that that all works, and that the previous kinds of options with different settings also still work. Use the latest code on the 'superanonymous' branch.

Documenting the changes will also eventually be needed.

**Comment by patrickmj** [comment]
@mebrett latest master has some text in the settings about anonymous contributions.

**Comment by mebrett** [comment]
@patrickmj Thanks, that looks better. Might be good to be particularly clear that the Anonymous option will ONLY work if non-registered is also checked. 

"This option will only work if non-registered contributions are allowed above; together the two settings let contributors remain completely anonymous, even to administrators. " or something like that.

Just to double check, is it feasible to only check "allow non registered" without checking anonymous (does it basically function like 'simple' at that point)?

**Comment by patrickmj** [comment]
Yep, 'allow non registered' should work like 'simple' when anonymous isn't checked

**Comment by mebrett** [comment]
Thanks. I've updated the markdown docs here: https://github.com/omeka/classic-enduser/blob/master/Plugins/Contribution_2.0.md#versions-x-and-above

Once we tweak the language on the Allow Non-Registered and Email settings, I'll add in some screenshots for the settings, and update the version number of the plugin.

**Comment by patrickmj** [comment]
If all the wording looks okay, I'll also need to update the translation stuff. Actual translation changes might or might not be ready for the new release, but we'll take what we have. Probably shouldn't update the version number and tag until we do that final step of pulling new translations down.

**Comment by mebrett** [comment]
Text for allow anon "A dummy user account will be created that stores no **identifyable** information" typo!

**Comment by mebrett** [comment]
Otherwise the texts look good to me.
