### ISSUE TITLE
Testing a few PRs

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Contribution#67]
We're finally trying to pull in a couple PRs. They should fix the anonymous contributor role, and make it possible to have more versatility on different contribution types combined with item types.

So, to test, pull the master branch of both Contribution and Omeka Classic.

1. Submit anonymous contributions

2. Set up different contribution types, reusing item types across them, and submit accordingly

**Comment by mebrett** [comment]
Most anonymous contributions are coming in fine and are locked so they can't be made public. All media works except video as noted in #68.
