### ISSUE TITLE
Drop-down for Item Type on Form broken in Explorer

### ISSUE THREAD

**Issue by wcaleb** [omeka/plugin-Contribution#70]
The Contribution form never appears in Internet Explorer, even after an Item Type is selected from the drop-down select menu.

My research suggests the problem is with [this line](https://github.com/omeka/plugin-Contribution/blob/master/views/public/javascripts/contribution-public-form.js#L29) in `contribution-public-form.js`.

Namely, `append()` is <a href="https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append">not supported in Internet Explorer</a>. This probably needs a polyfill or a refactoring but I'm not sure the best way to go about it.

**Comment by zerocrates** [comment]
`form` in this case is a jQuery object, so it's jQuery's `append` that's being called, not the DOM function you linked to.

Do you get an error implicating that line in the IE console? What version of IE is this (I'm assuming 11)?

**Comment by zerocrates** [comment]
I tried this out, just very quickly, and had no problem on IE 11.

**Comment by wcaleb** [comment]
I do get an error implicating that line and it just says it’s a syntax error. 

>

**Comment by zerocrates** [comment]
Is the site showing the problem available at some URL?

**Comment by wcaleb** [comment]
https://harveymemories.org/contribution

**Comment by zerocrates** [comment]
Yeah, I can confirm the issue on your site. This "syntax error" or other unspecified error nonsense is one of the worst parts of trying to deal with IE.

I _think_ what's happening is that it's actually complaining about what jQuery's doing when the append is called. The relevant bit of what it will do is execute any script blocks that came back from the AJAX request for the type form. You've got some custom stuff going on in there, namely scripts for running a datepicker widget and for adding some explanatory text to the map, it looks like.

If you look at the Network tab, you'll see IE downloads the datepicker JS file, but not the map explanation one, which comes later. This leads me to think that it's the datepicker JS that's actually the culprit.

[Looking at that datepicker script], my attention is drawn to the comments at the bottom: those are HTML comments. This is a common enough mistake that the other browsers apparently support them and don't even complain about them, but my guess would be that IE doesn't.

I'm actually a little surprised that the other browsers don't complain about this at all, but they don't (you can try putting an HTML  comment in the Chrome console, it just happily returns `undefined` and raises no error).

**Comment by zerocrates** [comment]
Actually now that I look at it, supporting HTML comments is actually [required](http://www.ecma-international.org/ecma-262/6.0/#sec-html-like-comments) by the standard. That's kind of sad.

Of course, IE doesn't actually support that version of the standard, so. Learn something every day.

![image](https://user-images.githubusercontent.com/298975/43930922-fc0a9f38-9c09-11e8-96e6-c9e25dd6d572.png)

**Comment by zerocrates** [comment]
whoops, that previous comment was supposed to actually link the script in question, it's this:

https://harveymemories.org/plugins/Contribution/views/public/javascripts/datepicker.js

**Comment by wcaleb** [comment]
I removed the comments from datepicker, and it now works! Can't believe that did it, but it did. Thank you very much for your help!
