### ISSUE TITLE
AdminTheme: Edit Elements in contribution types 

### ISSUE THREAD

**Issue by sharonmleon** [omeka/plugin-Contribution#72]
Seems like these element divs are blown out to multiple rows now, when they used to be pretty compact (see current docs: https://omeka.org/classic/docs/Plugins/Contribution/)

![Screen Shot 2021-08-17 at 3 50 32 PM](https://user-images.githubusercontent.com/741480/129791277-aab4c839-688f-4ec5-be11-9c2d67074782.png)

**Comment by kimisgold** [comment]
This has been addressed in the above commit and is ready for testing.

**Comment by sharonmleon** [comment]
Looks good!
