### ISSUE TITLE
No Tiny MCE Editor in the TOS input under Submission Settings Tab

### ISSUE THREAD

**Issue by sharonmleon** [omeka/plugin-Contribution#73]

**Comment by kimisgold** [comment]
This should be fixed and is ready for a look.

**Comment by sharonmleon** [comment]
So, I might be having an install problem, but after I pulled the changes, my Submissions Settings tab results in this error:

BadMethodCallException: Column pairs must be defined by _getColumnPairs() in order to use Omeka_Db_Table::findPairsForSelectForm()! in /home/sharonml/public_html/6floors.org/workshop/application/libraries/Omeka/Db/Table.php:262
Stack trace:
#0 /home/sharonml/public_html/6floors.org/workshop/application/libraries/Omeka/Db/Table.php(245): Omeka_Db_Table->_getColumnPairs()
#1 /home/sharonml/public_html/6floors.org/workshop/plugins/Contribution/controllers/SettingsController.php(144): Omeka_Db_Table->findPairsForSelectForm()
#2 /home/sharonml/public_html/6floors.org/workshop/plugins/Contribution/controllers/SettingsController.php(27): Contribution_SettingsController->_getForm()
#3 /home/sharonml/public_html/6floors.org/workshop/application/libraries/Zend/Controller/Action.php(516): Contribution_SettingsController->editAction()
#4 /home/sharonml/public_html/6floors.org/workshop/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('editAction')
#5 /home/sharonml/public_html/6floors.org/workshop/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /home/sharonml/public_html/6floors.org/workshop/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#7 /home/sharonml/public_html/6floors.org/workshop/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#8 /home/sharonml/public_html/6floors.org/workshop/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#9 /home/sharonml/public_html/6floors.org/workshop/admin/index.php(28): Omeka_Application->run()
#10 {main}

**Comment by sharonmleon** [comment]
Something I did resolved this error.

Things look good.
